version: '2.4'

services:
  passhport:
    image: frxyt/passhport:latest
    build:
      context: .
    container_name: passhport
    environment:
      - TZ=Europe/Paris
    hostname: passhport
    ports:
      - 127.0.0.1:22:22
      - 127.0.0.1:5000:5000
    volumes:
      - passhport_certs:/etc/passhport/certs:rw
      - passhport_db:/var/lib/passhport:rw
      - passhport_keys:/etc/ssh/keys:rw
      - passhport_log:/var/log/passhport:rw
      - passhport_ssh:/home/passhport/.ssh:rw

volumes:
  passhport_certs:
  passhport_db:
  passhport_keys:
  passhport_log:
  passhport_ssh: