#!/bin/sh

# Copyright (c) 2021 FEROX YT EIRL, www.ferox.yt <devops@ferox.yt>
# Copyright (c) 2021 Jérémy WALTHER <jeremy.walther@golflima.net>
# See <https://github.com/frxyt/docker-passhport> for details.

set -ex;

ALPINE_VERSION=alpine:3.13
docker_build_latest=yes

while read -r PASSHPORT_VERSION; do
    docker build \
        --build-arg ALPINE_VERSION=${ALPINE_VERSION} \
        --build-arg PASSHPORT_VERSION=${PASSHPORT_VERSION} \
        --build-arg SOURCE_BRANCH=${SOURCE_BRANCH} \
        --build-arg SOURCE_COMMIT=${SOURCE_COMMIT} \
        -f ${DOCKERFILE_PATH} -t ${DOCKER_REPO}:${PASSHPORT_VERSION} .
    if [ "${docker_build_latest}" = yes ]; then
        docker_build_latest=no
        docker tag ${DOCKER_REPO}:${PASSHPORT_VERSION}-${SOURCE_BRANCH} ${DOCKER_REPO}:latest
    fi
done < ./hooks/PASSHPORT_VERSIONS